version: '3.8'

services:
  mudo-stock-app:
    build: .
    container_name: mudo_stock_app
    ports:
      - "90:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs  # Log dosyaları için
    networks:
      - mudo-network

networks:
  mudo-network:
    driver: bridge
